### PR TITLE
Add missing service-08 to project file

### PR DESCRIPTION
**Pull request by michalkocon**

### CODE REVIEW

**Comment by michalkocon** [comment]
Sanity check passes on ASNIDE VM.

**Review by hcorg — APPROVED** [review]

**Comment by hcorg** [comment]
before merging we need to fix build on travis

seems that asn1scc is generating incorrect C code. Maybe different version should be used on Travis, if it works locally

**Comment by hcorg** [comment]
it does not pass on my machine...

**Comment by michalkocon** [comment]
Only thing I did was updating asn1scc, other packages are intact. I'll double check this

**Comment by hcorg** [comment]
I did not know asn1scc update is required.

**Comment by michalkocon** [comment]
I thought I've got the same version as travis. I'm on .24, and travis is .23.

**Pull request merged**
